[options]
; Set the admin password
admin_passwd = admin;

; Set the database connection settings
db_host = pg-2070256f-deltaee001-f127.k.aivencloud.com
db_port = 15608
db_sslmode = require
db_user = avnadmin
db_password = AVNS_wWuWx1-_6sX8ZMes4eL
db_name = postgres

; Set the timezone
timezone = UTC

; Set the addons paths
addons_path = addons

; Enable/disable debug mode
debug_mode = False
